name: Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: 📥 Restore dependencies
        run: dotnet restore --verbosity normal
      - name: 🔨 Build
        run: dotnet build --no-restore --verbosity normal
      - name: 📋 Test
        run: dotnet test --no-restore --verbosity normal
